### ISSUE TITLE
Missing values in TransactionBlockResponse

### ISSUE THREAD

**Issue by hyperschwartz** [mcxross/ksui#6]
I'm getting this error when calling attempting to run a `paySui` transaction through the `executeTransactionBlock` function:
```
Exception in thread "main" kotlinx.serialization.MissingFieldException: Fields [timestampMs, checkpoint] are required for type with serial name 'xyz.mcxross.ksui.model.TransactionBlockResponse', but they were missing at path: $
```

Upon further inspection, I saw that my output payload didn't include those fields at all (as expected from the error).  I looked at the Sui source code, and it appears that those fields are optional: https://github.com/MystenLabs/sui/blob/acbf77f807ecc04cb0c44c521abf5c2bbc1a2a9d/crates/sui-json-rpc-types/src/sui_transaction.rs#L209

I believe the fix is to modify the `TransactionBlockResponse` class to make `timestampMs` and `checkpoint` nullable `Long?` fields.  I'm still very new to Sui, so I may be doing something wrong that is perhaps causing these fields to be missing when they shouldn't be.  Any insights into this issue would be incredibly valuable to me!  Thank you.

**Comment by hyperschwartz** [comment]
Update: I've been doing more experimentation with this.  In my initial use-case, I was sending a tx and immediately trying to query its TransactionBlockResponse when its tx digest appeared on my event stream.  It appears that the transaction can be pulled immediately from chain when it appears on the stream, but the timestamp and checkpoint values are not available.  I made my code do a wait/backoff strategy when deserialization fails, and this fixed my problem - those timestamp and checkpoint values become available very shortly after the digest appears in the stream.

With the cause of the issue now known, I still believe that this fix is useful, because the response is still valid before the ts and checkpoint are stored.

**Comment by astinz** [comment]
This has been fixed in the upcoming release; the defaults have been handled reasonably. 
The version will be available on central by 31/12/2013 and will be the last version to support Sui RPC v1 as we work towards v2.
